#!/bin/bash
set -e

function usage() {
cat << EOD
localci [<options>] [--] <commit>...

--help      show help page
--version   show version page
EOD
}

function version() {
cat << EOD
localci (unversioned)

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
EOD
}

function timestamp() {
echo -ne "\033[1;36m"
date
echo -ne "\033[0m"
}

commits=()
do_positional_arguments=no
for argument in "$@"
do
    if [[ "$do_positional_arguments" = "yes" ]]
    then
        commits+=("$argument")
        continue
    fi

    case "$argument"
    in
    --help)
        usage
        exit
        ;;
    --version)
        version
        exit
        ;;
    --)
        do_positional_arguments=yes
        ;;
    *)
        commits+=("$argument")
        do_positional_arguments=yes
        ;;
    esac
done

timestamp

if [[ ${#commits[@]} -eq 0 ]]
then
    timestamp
    exit
fi

readarray -t commits < <(git rev-list --reverse --boundary ${commits[@]})

saved_ref=$(git symbolic-ref --short HEAD)
for commit in "${commits[@]#-}"
do
    git switch --detach "$commit"

    cd Build

    if ninja install
    then
        echo -e "\033[1;32msuccess $commit\033[0m"
    else
        echo -e "\033[1;31mfailure $commit\033[0m"

        timestamp
        exit 1
    fi

    cd ..
done

timestamp

git switch "$saved_ref"
